### ISSUE TITLE
Things I stumbled on

### ISSUE THREAD

**Issue by krainboltgreene** [wahlfeld/valheim-on-aws#18]
Hey great project, just want to publish some notes on what I stumbled against:

  1. There's a few deprecation notices for S3-apis in terraform
  2. The output doesn't tell you the valheim address
  3. xbox game pass support obviously not detailed

I'm working through these now, will update as I fix.

**Comment by wahlfeld** [comment]
I'll try look at the TF soon and update to the latest version and providers if I can. There is a TF output that's meant to show you the server URL for monitoring.. is that what you mean by Valheim address? Otherwise, the server name should just be what the user adds to the inputs. Could output that as well I guess, but seemed redundant. Xbox Game Pass ... yeah, I don't personally use that so would have to work out what the differences are. Presumably, the server-side parts wouldn't be any different, as the Xbox Game Pass version is just client-side.

**Comment by wahlfeld** [comment]
I've updated the TF version including several S3 resources. Valheim server name has been added to the TF outputs (assuming that's what you meant). Can't do much about Xbox Game Pass at the moment, however PRs welcome.
