### ISSUE TITLE
How to use custom domain?

### ISSUE THREAD

**Issue by Nipplechips** [wahlfeld/valheim-on-aws#22]
Are there any resources on how a custom domain name is supposed to work with this setup?  I can see a space for the domain in `inputs.tf` but cannot see how this domain will be pointed to the EC2 instance automatically without the use of a ALB/NLB.

Sorry if I have missed an obvious explanation.

**Comment by wahlfeld** [comment]
The code that maps a domain name to your server is [here](https://github.com/wahlfeld/valheim-on-aws/blob/main/module/local/update_cname.sh) and [here](https://github.com/wahlfeld/valheim-on-aws/blob/main/module/local/update_cname.json). 

It's only temporary, i.e. so long as your EC2 instance doesn't change, as it's the Terraform that creates the mapping between a CNAME using your domain, and the public domain name of the EC2 instance. You may find that it's not that useful due to the fact it can change, and perhaps an easier more reliable way would be the use the AWS app, and then navigate to the EC2 details to find the current IP address or public DNS. Then just add the port number to the end of the URL `:19999`.

**Comment by wahlfeld** [comment]
Thinking about this some more, I could incorporate running the script whenever the Valheim service starts which would mean the monitoring URL would still work even if the instance changed, e.g., due to Spot interruption.

**Comment by wahlfeld** [comment]
> Thinking about this some more, I could incorporate running the script whenever the Valheim service starts which would mean the monitoring URL would still work even if the instance changed, e.g., due to Spot interruption.

Added in [6b28315](https://github.com/wahlfeld/valheim-on-aws/commit/6b28315afa47b2b016271d6210f0de5bac0dc5ef)

**Comment by wahlfeld** [comment]
> Thinking about this some more, I could incorporate running the script whenever the Valheim service starts which would mean the monitoring URL would still work even if the instance changed, e.g., due to Spot interruption.

Added in [6b28315](https://github.com/wahlfeld/valheim-on-aws/commit/6b28315afa47b2b016271d6210f0de5bac0dc5ef)
