### ISSUE TITLE
Player count and modding

### ISSUE THREAD

**Issue by Dreathorian** [wahlfeld/valheim-on-aws#60]
Hey, first of all thank you for this repo.

I just started playing this game this weekend and quickly realized that this will hopefully be my number one go to :-)

2 questions pop up for me:

1. is it scalable? if not what tiers to you recommend for player count ranges?
2. how do mods impact the servers and how can i adjust for that?

Thanks in advance!

P.S. if I come across as a little dull, I apologize, i only slept a couple of hours this weekend ;-)

**Comment by wahlfeld** [comment]
So I run my server with 4 players on the default instance type t3a.medium for several hours without issue. Valheim has a limit of 10 players so the scalability limitation is with the game, rather than this server implementation. You may need to use a t3a.large or equivalent instance type for 10 players, but I can't confirm as I've never tried.

I use a number of mods myself (client-side) which are happily accepted by the server. Other players "see" your mods if they affect the world around them which can be interesting. Every now and then a mod will cause issues/bugs in the server but it's usually pretty obvious which ones are the culprit. When Valheim is patched the mods usually need patching too, else they may be incompatible with the changes. Modders usually sort this within a week or so for active mods.

Hope that helps!
